apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-desec
spec:
  acme:
    # Use Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@example.com
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - dns01:
        webhook:
          # Must match the groupName in values.yaml
          groupName: acme.example.com
          solverName: libdns
          config:
            provider: desec
            secretRef:
              name: desec-credentials
              namespace: cert-manager
